#pragma once

enum LoginFailReason
{
    REASON_SUCCESS = 0x0,
    REASON_SYSTEM_ERROR_LOGIN_LATER = 0x1,
    REASON_PASS_WRONG = 0x2,
    REASON_USER_OR_PASS_WRONG = 0x3,
    REASON_ACCESS_FAILED_TRY_AGAIN_LATER = 0x4,
    REASON_ACCOUNT_INFO_INCORRECT_CONTACT_SUPPORT = 0x5,
    REASON_ACCOUNT_IN_USE = 0x7,
    REASON_IP_SESSION_REJECTED = 0x8,
    REASON_INVALID_STATE = 0xA,
    REASON_SERVER_OVERLOADED = 0xF,
    REASON_UNDER_18_YEARS_KR = 0xC,
    REASON_SERVER_MAINTENANCE = 0x10,
    REASON_TEMP_PASS_EXPIRED = 0x11,
    REASON_USAGE_TERM_EXPIRED = 0x12,
    REASON_NO_TIME_LEFT = 0x13,
    REASON_SYSTEM_ERROR = 0x14,
    REASON_ACCESS_FAILED = 0x15,
    REASON_RESTRICTED_IP = 0x16,
    REASON_DUAL_BOX = 0x23,
};
